### ISSUE TITLE
How to run lighthouse tests on desktop viewport?

### ISSUE THREAD

**Issue by mdcruz** [mfrachet/cypress-audit#37]
Hi! First of all, thank you so much for this plugin. Been playing around with it and it's really great 👍 

I noticed though that when I invoke `cy.lighthouse()`, by default this runs the lighthouse test on mobile view. Please see attached image as reference

![cy-lighthouse 2020-10-28 15_44_23](https://user-images.githubusercontent.com/10811379/97460291-8973e600-1934-11eb-8535-835c2e5b9de3.gif)

I tried passing in the lighthouse config but it didn't work 

```
const thresholds = {
        "performance": 50,
        "accessibility": 80,
        "best-practices": 50,
        "seo": 60,
        "pwa": 50
    };
     
    const lighthouseConfig = {
      "ci": {
        "collect": {
          "settings": {
            "chromeFlags": '--no-sandbox',
            "emulatedFormFactor": 'desktop'
          }
        }
      }
    };

    cy.lighthouse(thresholds, lighthouseConfig);
```
Any pointers on how to do it on desktop would be appreciated :) thank you!

**Comment by mfrachet** [comment]
Hello there and thank you for the kind words, really appreciated 🙏 .

I managed to run the tests on desktop by using the following:

```javascript
 cy.lighthouse(
      {
        accessibility: 90,
        "best-practices": 50,
        seo: 50,
        pwa: 50,
      },
      { emulatedFormFactor: "mobile" }
    );
```

Let me know if it's helpful (or not 😓 )

**Comment by mdcruz** [comment]
Thanks @mfrachet this works! 👍

**Comment by MuckT** [comment]
Recent changes to lighthouse appear to have changed this:
```
cy.lighthouse(
      {
        accessibility: 85,
        'best-practices': 93,
        seo: 50,
        pwa: 50,
      },
      {
        formFactor: 'desktop',
        screenEmulation: {
          mobile: false,
          width: 1350,
          height: 940,
          deviceScaleFactor: 1,
          disabled: false,
        },
      });
    })

**Comment by mfrachet** [comment]
Ooooh, I'm so sorry for this :( . I've released the last version way too fast and didn't thought about the breaking chnages :(.

I've made the v0.2.4 deprecated and published a version that you can use with the previous lighthouse versions on v0.2.5. I've also published a v0.3.0 that has the updated Lighthouse version.

I've published those 5mns ago so it may take time for NPM to show them.

Sorry for this :(

**Comment by devhid** [comment]
Hey, I'm trying to use the new config option in Lighthouse, `preset: 'desktop'` to use the desktop configuration, but it still shows the mobile viewport when I run the tests. Does the current version of cypress-audit support that option?
